export const GIFS_EJERCICIOS: Record<string, string> = {
    "3/4 sit-up": "/gifs/3_4_sit_up.gif",
    "air bike": "/gifs/air_bike.gif",
    "assisted pull-up": "/gifs/assisted_pull_up.gif",
    "assisted triceps dip (kneeling)": "/gifs/assisted_triceps_dip_kneeling.gif",
    "barbell bench press": "/gifs/barbell_bench_press.gif",
    "barbell bench squat": "/gifs/barbell_bench_squat.gif",
    "barbell bent over row": "/gifs/barbell_bent_over_row.gif",
    "barbell close-grip bench press": "/gifs/barbell_close_grip_bench_press.gif",
    "barbell curl": "/gifs/barbell_curl.gif",
    "barbell deadlift": "/gifs/barbell_deadlift.gif",
    "barbell drag curl": "/gifs/barbell_drag_curl.gif",
    "barbell front raise": "/gifs/barbell_front_raise.gif",
    "barbell front squat": "/gifs/barbell_front_squat.gif",
    "barbell incline bench press": "/gifs/barbell_incline_bench_press.gif",
    "barbell lunge": "/gifs/barbell_lunge.gif",
    "barbell lying triceps extension skull crusher": "/gifs/barbell_lying_triceps_extension_skull_crusher.gif",
    "barbell overhead squat": "/gifs/barbell_overhead_squat.gif",
    "barbell preacher curl": "/gifs/barbell_preacher_curl.gif",
    "barbell press sit-up": "/gifs/barbell_press_sit_up.gif",
    "barbell pullover": "/gifs/barbell_pullover.gif",
    "barbell rear delt raise": "/gifs/barbell_rear_delt_raise.gif",
    "barbell seated overhead press": "/gifs/barbell_seated_overhead_press.gif",
    "barbell squat (on knees)": "/gifs/barbell_squat_on_knees.gif",
    "barbell straight leg deadlift": "/gifs/barbell_straight_leg_deadlift.gif",
    "cable bar lateral pulldown": "/gifs/cable_bar_lateral_pulldown.gif",
    "cable cross-over variation": "/gifs/cable_cross_over_variation.gif",
    "cable high row (kneeling)": "/gifs/cable_high_row_kneeling.gif",
    "cable low seated row": "/gifs/cable_low_seated_row.gif",
    "dumbbell lying femoral": "/gifs/dumbbell_lying_femoral.gif",
    "lever lying leg curl": "/gifs/lever_lying_leg_curl.gif"
  };  